/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BuildingSchema extends BaseModel {
  static $columns = ['address', 'city', 'createdAt', 'id', 'name', 'postalCode', 'updatedAt'] as const
  $columns = BuildingSchema.$columns
  @column()
  declare address: string
  @column()
  declare city: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare postalCode: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProviderSchema extends BaseModel {
  static $columns = ['companyName', 'createdAt', 'geranceId', 'id', 'isActive', 'phone', 'speciality', 'updatedAt', 'userId'] as const
  $columns = ProviderSchema.$columns
  @column()
  declare companyName: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare geranceId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare phone: string | null
  @column()
  declare speciality: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column()
  declare key: string
  @column()
  declare points: number
}

export class SessionSchema extends BaseModel {
  static $columns = ['data', 'expiresAt', 'id', 'userId'] as const
  $columns = SessionSchema.$columns
  @column()
  declare data: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
}

export class TicketAttachmentSchema extends BaseModel {
  static $columns = ['checksumSha256', 'createdAt', 'filePath', 'id', 'mimeType', 'originalName', 'sizeBytes', 'storageDriver', 'storageKey', 'ticketId', 'updatedAt', 'userId'] as const
  $columns = TicketAttachmentSchema.$columns
  @column()
  declare checksumSha256: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare filePath: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mimeType: string
  @column()
  declare originalName: string
  @column()
  declare sizeBytes: number
  @column()
  declare storageDriver: string | null
  @column()
  declare storageKey: string | null
  @column()
  declare ticketId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TicketCommentSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'id', 'isInternal', 'ticketId', 'updatedAt', 'userId'] as const
  $columns = TicketCommentSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isInternal: boolean
  @column()
  declare ticketId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TicketSchema extends BaseModel {
  static $columns = ['assignedTo', 'category', 'createdAt', 'description', 'id', 'priority', 'providerId', 'reference', 'resolvedAt', 'status', 'title', 'unitId', 'updatedAt', 'userId'] as const
  $columns = TicketSchema.$columns
  @column()
  declare assignedTo: number | null
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare priority: string
  @column()
  declare providerId: number | null
  @column()
  declare reference: string | null
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column()
  declare unitId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UnitSchema extends BaseModel {
  static $columns = ['buildingId', 'createdAt', 'floor', 'id', 'label', 'type', 'updatedAt'] as const
  $columns = UnitSchema.$columns
  @column()
  declare buildingId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare floor: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare label: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserUnitSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'relation', 'unitId', 'updatedAt', 'userId'] as const
  $columns = UserUnitSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare relation: string
  @column()
  declare unitId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'firstName', 'id', 'inviteToken', 'inviteTokenExpiresAt', 'lastName', 'notificationPreference', 'password', 'phone', 'role', 'status', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare firstName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inviteToken: string | null
  @column.dateTime()
  declare inviteTokenExpiresAt: DateTime | null
  @column()
  declare lastName: string | null
  @column()
  declare notificationPreference: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare phone: string | null
  @column()
  declare role: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
